name: PandoraEnchants
version: ${project.version}
main: me.nanigans.pandoraenchants.PandoraEnchants
authors: [ProNanigans]
description: Custom Minecraft Enchantments for PandoraPVP
depend: [ArmorEvent]
commands:
  gemenchant:
    usage: /gemenchant <player> <gem type>
    description: Gives the player a specific gem
    aliases: [gemgive, givegem]
  addcustomenchant:
    usage: /addcustomenchant
    description: Opens up the GUI for converting armor and weapons
  enchantreload:
    usage: /enchantreload
    description: Reload all enchantments
permissions:
  Enchants.GiveGem:
    description: Allows a user to give a player a gem
    default: op
  Enchants.OpenGUI:
    description: Allows a user to open the enchant gui
    default: op
  Enchants.Reload:
    default: op
    description: Allows the user to reload enchantments